// ============================================================
// Sahaba Club — Upcoming Events
// ------------------------------------------------------------
// This is the ONLY file you need to touch to add or remove an
// event on the Events page. Order doesn't matter — events are
// sorted by date automatically, and anything with a date in the
// past is hidden automatically too.
//
// To add a new event, copy this block and fill in your details,
// then add it to the EVENTS array below (comma-separated):
//
// {
//   title: "Event Title",
//   country: "Country",
//   location: "City / Venue",
//   date: "2026-09-15",       // YYYY-MM-DD
//   time: "6:00 PM GST",      // shown as-is, any format you like
//   price: "Free",            // "Free" or "Paid" (e.g. "Paid — $28")
//   mode: "In-Person",        // "In-Person" or "Online"
//   tags: ["AI", "Cloud"],    // optional — up to 2 subject tags shown as badges
//   registerLink: "https://example.com/register",  // optional — shows a "Register" button
//   mapsLink: "https://www.google.com/maps/search/?api=1&query=Venue+Name",  // optional — shows a "Find Location" button (In-Person only)
//   image: "https://... or assets/events/photo.jpg",  // optional
//   brand: "microsoft",       // optional — if set and no image, shows an official-training placeholder graphic
//   description: "Optional 1-2 sentence blurb.",       // optional
// }
// ============================================================

var EVENTS = [
  {
    title: "AI Cafe by AIQUAINT ☕",
    country: "UAE",
    location: "Starbucks, Emirates Office Tower, Trade Center, Dubai",
    date: "2026-07-25",
    time: "10:00 AM – 11:00 AM",
    price: "Free",
    mode: "In-Person",
    tags: ["AI", "Startups"],
    registerLink: "https://luma.com/5pzl9z2x",
    mapsLink: "https://www.google.com/maps/search/?api=1&query=Starbucks%20Emirates%20Towers%20Dubai",
    image: "https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,dpr=1,anim=false,background=white,quality=75,width=800,height=420/event-social/ct/f44167f2-939c-4ef6-bb36-fc8566935f80.png",
    description: "An intimate, no-slides coffee chat for AI folks — founders, builders, and researchers talking honestly about what's really happening in AI right now. Limited seats, real conversations, zero panels.",
  },
  {
    title: "Founder Stories: The Journey Behind the Startup",
    country: "UAE",
    location: "Bookends, Dubai",
    date: "2026-07-25",
    time: "12:30 PM – 2:00 PM",
    price: "Free",
    mode: "In-Person",
    tags: ["Startups", "Business"],
    registerLink: "https://luma.com/f8vyi1kp",
    mapsLink: "https://www.google.com/maps/search/?api=1&query=Bookends%20Dubai",
    image: "https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,dpr=1,anim=false,background=white,quality=75,width=800,height=420/event-social/j4/aa20f2a3-db05-4a89-a338-07ac219fae2a.png",
    description: "Honest, unscripted conversations with three UAE founders about the wins, the mistakes, and the pivots — no pitches, no lectures. Just real startup stories, audience Q&A, coffee, and community.",
  },
  {
    title: "UAE | MENA Software Engineers & QA Weekly Meetup",
    country: "UAE",
    location: "Dubai (exact address shared after registration)",
    date: "2026-07-26",
    time: "9:30 AM – 1:00 PM",
    price: "Free",
    mode: "In-Person",
    tags: ["Coding", "AI"],
    registerLink: "https://luma.com/e2shzo9m",
    mapsLink: "https://www.google.com/maps/search/?api=1&query=25.21797176775973%2C55.28058148947743",
    image: "https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,dpr=1,anim=false,background=white,quality=75,width=800,height=420/event-social/ep/91ce8d1b-8c1a-4787-b60f-c8891221d883.png",
    description: "A weekly gathering for software engineers and QA folks across the UAE and MENA to connect, share, and grow together — this session dives into event-driven architecture, with a talk from Future Communications Company, Kuwait. Capacity capped at 35, so register early.",
  },
  {
    title: "AI.TV Community Meet-Up",
    country: "UAE",
    location: "Web3 Productions, Dubai",
    date: "2026-07-30",
    time: "6:30 PM – 9:00 PM",
    price: "Free",
    mode: "In-Person",
    tags: ["AI", "Media"],
    mapsLink: "https://www.google.com/maps/search/?api=1&query=Web3%20Productions&query_place_id=ChIJ4SrR5t1tXz4Rrt7TKiVDaf4",
    image: "assets/events/aitv-community-meetup.avif",
    description: "Welcome to the home of AI creatives in the UAE. Hosted by AI.TV in partnership with ByteDance and Curious Refuge, this is your spot to meet, learn, share, and connect with fellow AI filmmakers and creatives. Open to anyone curious about AI filmmaking — all levels welcome.",
  },
  {
    title: "Build with n8n, Deploy in Minutes",
    country: "UAE",
    location: "Emirates Towers, Sheikh Zayed Rd, Dubai",
    date: "2026-08-01",
    time: "5:00 PM – 7:00 PM",
    price: "Free",
    mode: "In-Person",
    tags: ["Agentic", "Coding"],
    registerLink: "https://luma.com/n8n-easydep",
    mapsLink: "https://www.google.com/maps/search/?api=1&query=Emirates%20Towers%20Sheikh%20Zayed%20Rd&query_place_id=ChIJy95l7pJCXz4RpIBbqDIVc78",
    image: "https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,dpr=1,anim=false,background=white,quality=75,width=800,height=420/event-social/0z/4440f6bc-33b4-4dde-865a-c8e3f949f616.png",
    description: "A hands-on session on shipping automations fast — live demos building an n8n workflow and deploying it with EasyDep, plus deployment best practices you can actually use. Pizza included.",
  },
  {
    title: "Founders Meetup - Dubai",
    country: "UAE",
    location: "WeWork, Dubai",
    date: "2026-08-05",
    time: "3:00 PM – 4:00 PM",
    price: "Free",
    mode: "In-Person",
    tags: ["Startups", "Business"],
    registerLink: "https://luma.com/jwuy4ni0",
    mapsLink: "https://www.google.com/maps/search/?api=1&query=WeWork%20Dubai",
    image: "https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,dpr=1,anim=false,background=white,quality=75,width=800,height=420/event-social/uo/995bb1c9-5b7d-40ae-ba53-3d7ed3a387ab.png",
    description: "A relaxed meetup for founders and startup enthusiasts to swap stories, find collaborators, and build real relationships with fellow builders in Dubai.",
  },
  {
    title: "AI Business, Investment & Professional Meetup",
    country: "UAE",
    location: "JLT, Dubai",
    date: "2026-08-06",
    time: "6:30 PM – 8:30 PM",
    price: "Free",
    mode: "In-Person",
    tags: ["AI", "Startups"],
    registerLink: "https://luma.com/st1efdgi",
    mapsLink: "https://www.google.com/maps/search/?api=1&query=JLT%20Dubai",
    image: "https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,dpr=1,anim=false,background=white,quality=75,width=800,height=420/event-social/is/3446b86b-9c1d-4d65-9720-f7f7ebde72d8.png",
    description: "A high-signal evening for builders, founders, and investors to swap ideas and spark collaborations — plus live AI demos from the DDS AI Challenge and the launch of the DDS Business Circle.",
  },
  {
    title: "Dubai AI Hub — Builder Lab #3: Voice Agents Hackathon",
    country: "UAE",
    location: "Dubai (venue TBA)",
    date: "2026-08-08",
    time: "8:30 AM – 5:30 PM",
    price: "Free",
    mode: "In-Person",
    tags: ["AI", "Hackathon"],
    registerLink: "https://luma.com/hai59p7q",
    image: "https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,dpr=1,anim=false,background=white,quality=75,width=800,height=420/event-social/9b/58038cb0-2fd5-4b9d-89d9-59425aa40ae7.png",
    description: "A one-day hackathon backed by ElevenLabs, Devin, and context.dev — build a voice-first AI agent that pulls live web data and actually talks back. Teams of five, free credits from every sponsor, real prizes on the line.",
  },
  {
    title: "Deal Catch: Pitch & Networking in Dubai",
    country: "UAE",
    location: "Josephs Cafe, Dubai",
    date: "2026-08-12",
    time: "7:00 PM – 9:30 PM",
    price: "Paid — $28",
    mode: "In-Person",
    tags: ["Startups", "Investors"],
    registerLink: "https://luma.com/6pvfpqjx",
    mapsLink: "https://www.google.com/maps/search/?api=1&query=Josephs%20Cafe%20Dubai",
    image: "https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,dpr=1,anim=false,background=white,quality=75,width=800,height=420/event-social/i7/5e6c7b54-3667-441c-83fc-c03a91a2a9ce.png",
    description: "Pre-selected founders pitch live to a room of investors and professionals, hosted by Olivier Club and Fishman VC after 7 years of private events — now going public. Built for founders, VCs, angels, and anyone growing their network in Dubai's startup scene.",
  },
  {
    title: "Crazy Clauders — B2B Networking for Founders & Business Owners",
    country: "UAE",
    location: "Wild Woven, DIFC / Downtown, Dubai",
    date: "2026-08-25",
    time: "6:30 PM – 8:00 PM",
    price: "Free",
    mode: "In-Person",
    tags: ["AI", "Coding"],
    registerLink: "https://luma.com/skn8qvje",
    mapsLink: "https://www.google.com/maps/search/?api=1&query=Wild%20Woven%20DIFC%20Dubai",
    image: "https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,dpr=1,anim=false,background=white,quality=75,width=800,height=420/event-social/e7/4f227084-096e-435a-89dc-cbd6e63fbb66.png",
    description: "Dubai's first-ever Clauders meetup, for founders and builders shipping with Claude and other AI tools. Show off what you've built, meet fellow Clauders, and grab a drink — on you, as a thanks to the host for the space.",
  },
  {
    title: "n8n Hackathon: Automate with K2",
    country: "UAE",
    location: "Emirates Towers, Sheikh Zayed Rd, Dubai",
    date: "2026-08-29",
    time: "2:00 PM – 7:00 PM",
    price: "Free",
    mode: "In-Person",
    tags: ["AI", "Agentic"],
    registerLink: "https://luma.com/n8n-wuqj",
    mapsLink: "https://www.google.com/maps/search/?api=1&query=Emirates%20Towers%20Sheikh%20Zayed%20Rd&query_place_id=ChIJy95l7pJCXz4RpIBbqDIVc78",
    image: "https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,dpr=1,anim=false,background=white,quality=75,width=800,height=420/event-social/5h/9d74724b-e028-4269-869f-b8559105029e.png",
    description: "An n8n community hackathon focused on building automations with K2 — hosted by the n8n team and IFM Community. Hands-on building, real workflows, and a room full of automation builders.",
  },
  {
    title: "Runway — 4th Annual AI Film Festival",
    country: "UAE",
    location: "in5 Media, Dubai",
    date: "2026-09-01",
    time: "6:30 PM – 9:30 PM",
    price: "Free",
    mode: "In-Person",
    tags: ["AI", "Media"],
    registerLink: "https://luma.com/hpnd614f",
    mapsLink: "https://www.google.com/maps/search/?api=1&query=in5%20Media%20Dubai",
    image: "https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,dpr=1,anim=false,background=white,quality=75,width=800,height=420/event-social/tq/2e7e1c63-55f0-4166-ae3c-755dbd3a0e9d.png",
    description: "A curated screening of the winning films from Runway's AI Film Festival, followed by relaxed networking with filmmakers, creators, and commercial pros. Co-hosted by Yohan Wadia Studio and In5 — an evening of film, tech, and creativity.",
  },
  {
    title: "Microsoft Virtual Training Day: Transform Customer Experiences with AI",
    country: "Online",
    location: "Microsoft Digital Event",
    date: "2026-07-27",
    time: "7:30 AM – 8:45 AM GST",
    price: "Free",
    mode: "Online",
    tags: ["AI", "Business"],
    brand: "microsoft",
    registerLink: "https://msevents.microsoft.com/event?id=2978625225",
    description: "A free Microsoft Learn training on using Copilot and agents in Dynamics 365 Sales and Customer Service to close deals faster, boost team productivity, and deliver more personalized customer experiences. Completing it unlocks 50% off the related certification exam.",
  },
  {
    title: "Microsoft Virtual Training Day: Introduction to Microsoft Azure",
    country: "Online",
    location: "Microsoft Digital Event",
    date: "2026-07-27",
    time: "7:30 AM – 11:45 AM GST",
    price: "Free",
    mode: "Online",
    tags: ["Cloud", "Security"],
    brand: "microsoft",
    registerLink: "https://msevents.microsoft.com/event?id=2727739274",
    description: "A foundational, free Microsoft training covering core cloud concepts and Azure's compute, networking, storage, identity, and security services — plus governance and cost-control tools. Finish it and get 50% off the Azure Fundamentals certification exam.",
  },
  {
    title: "Agent in a Day",
    country: "Online",
    location: "Microsoft Digital Event (delivered with Koenig Solutions)",
    date: "2026-07-27",
    time: "5:00 AM – 1:00 PM GST",
    price: "Free",
    mode: "Online",
    tags: ["Agentic", "AI"],
    brand: "microsoft",
    registerLink: "https://msevents.microsoft.com/event?id=1844909682",
    description: "A full-day, hands-on workshop teaching anyone — business folks or developers — how to build agents fast with Microsoft Copilot Studio, with step-by-step labs and a Microsoft Certified Partner guiding you through it.",
  },
  {
    title: "Microsoft AI Envisioning Day: Publishing and Releasing Your AI Agent Solution",
    country: "Online",
    location: "Microsoft Digital Event",
    date: "2026-07-28",
    time: "7:30 AM – 8:30 AM GST",
    price: "Free",
    mode: "Online",
    tags: ["Agentic", "Cloud"],
    brand: "microsoft",
    registerLink: "https://msevents.microsoft.com/event?id=279903695",
    description: "A free Microsoft session on turning your AI agent into a market-ready SaaS offering — multitenant architecture, the Microsoft Foundry and Azure Marketplace publishing workflow, and everything else it takes to launch on the commercial marketplace.",
  },
  {
    title: "Get Started with Microsoft 365 Copilot",
    country: "Online",
    location: "Microsoft Digital Event",
    date: "2026-07-28",
    time: "7:30 AM – 8:45 AM GST",
    price: "Free",
    mode: "Online",
    tags: ["AI", "Business"],
    brand: "microsoft",
    registerLink: "https://msevents.microsoft.com/event?id=923449318",
    description: "A free, foundational Microsoft session on getting real productivity out of Copilot — summarizing Teams chats, drafting in Word, building PowerPoint decks, and writing better prompts, straight from Microsoft experts.",
  },
  {
    title: "Microsoft 365 Copilot Training for IT",
    country: "Online",
    location: "Microsoft Digital Event",
    date: "2026-07-28",
    time: "9:00 AM – 10:15 AM GST",
    price: "Free",
    mode: "Online",
    tags: ["AI", "Coding"],
    brand: "microsoft",
    registerLink: "https://msevents.microsoft.com/event?id=76801058",
    description: "A free Microsoft training built for IT professionals — using Copilot to build project plans, analyze asset data in Excel, tighten up technical docs in Word, and summarize findings for stakeholders faster.",
  },
  {
    title: "Microsoft 365 Copilot Training for Sales",
    country: "Online",
    location: "Microsoft Digital Event",
    date: "2026-07-28",
    time: "10:30 AM – 11:30 AM GST",
    price: "Free",
    mode: "Online",
    tags: ["AI", "Business"],
    brand: "microsoft",
    registerLink: "https://msevents.microsoft.com/event?id=3587052657",
    description: "A free Microsoft session for sales teams on using Copilot as an AI assistant — synthesizing sales activity from Teams, analyzing forecasts, and drafting promotions across Word, Outlook, and PowerPoint.",
  },
  {
    title: "Microsoft 365 Copilot Training for Executives",
    country: "Online",
    location: "Microsoft Digital Event",
    date: "2026-07-28",
    time: "11:30 AM – 12:30 PM GST",
    price: "Free",
    mode: "Online",
    tags: ["AI", "Business"],
    brand: "microsoft",
    registerLink: "https://msevents.microsoft.com/event?id=1150827960",
    description: "A free Microsoft session built for executives — using Copilot to synthesize project updates in Teams, write executive briefings in Word, model budget forecasts in Excel, and get a Business Insights agent working for you.",
  },
  {
    title: "Microsoft 365 Copilot Training for Legal",
    country: "Online",
    location: "Microsoft Digital Event",
    date: "2026-07-28",
    time: "1:00 PM – 2:00 PM GST",
    price: "Free",
    mode: "Online",
    tags: ["AI", "Business"],
    brand: "microsoft",
    registerLink: "https://msevents.microsoft.com/event?id=3553704114",
    description: "A free Microsoft session for legal professionals — using Copilot to summarize multi-page contracts, flag risk, track regulatory updates, and draft policy documents, with nuanced prompting techniques built for legal work.",
  },
];
