// Give every public page a share preview.
//
//   node tools/add-og-tags.mjs          report what is missing
//   node tools/add-og-tags.mjs --apply  insert it
//
// ============================================================
// Why
// ============================================================
//
// Ahmed: "Make sure when I share to linkedin or Facebook or even whatsapp to
// have nice image, branding for Sahaba Club website and clear catchy post".
//
// Checked before writing anything: `event.html` was the ONLY page on the site
// with an og:image, and it pointed at `assets/icon-512.png` — a SQUARE app
// icon. LinkedIn and Facebook lay out a card at 1.91:1; handed a square they
// fall back to a small thumbnail beside a line of text. So every link anyone
// has ever shared from this site has unfurled either unbranded or bare.
//
// The homepage, events, membership, the podcast and EduHackAI had no og tags
// at all.
//
// ============================================================
// What this does NOT solve
// ============================================================
//
// ⚠ The preview is PER PAGE, not per event. A shared event link still unfurls
// as "AI Events — Sahaba Club" with the generic card, because this is a static
// host: the HTML is identical for every event and crawlers never run the
// JavaScript that fetches the real one. The note in event.html's <head> has
// said so since the page was written and it is still true.
//
// Fixing that needs a build step that writes one HTML file per event and
// re-runs whenever an event changes — and events are added through the admin
// panel, not through git, so it would go stale between deploys unless the
// deploy is triggered by the database. Worth doing, bigger than this file, and
// deliberately not started here.

import { readFileSync, writeFileSync } from "node:fs";

const ORIGIN = "https://www.sahabaclub.ai";
const CARD = ORIGIN + "/assets/og-events.jpg";

// One entry per public page. The description is what actually appears under
// the headline in a LinkedIn or WhatsApp preview, so it is written to be read
// by a person deciding whether to click — not stuffed with keywords.
const PAGES = [
  {
    file: "index.html",
    title: "Sahaba Club — The AI universe in the shape of a club",
    desc: "A global community for AI and cloud. Coaching, hackathons, PromptArena, podcasts and events — join free and get Microsoft 365 for 3 months.",
    url: ORIGIN + "/",
  },
  {
    file: "events.html",
    title: "AI Events Universe — Sahaba Club",
    desc: "Every AI event worth knowing about, in one place: hackathons, meetups and the region's landmark conferences. Filter by organizer, country and format.",
    url: ORIGIN + "/events.html",
  },
  {
    file: "events-hub.html",
    title: "Sahaba Club Events Hub",
    desc: "Events run by Sahaba Club and its partners — what is coming up, and everything we have hosted so far.",
    url: ORIGIN + "/events-hub.html",
  },
  {
    file: "membership.html",
    title: "Membership — Sahaba Club",
    desc: "Join free and get Microsoft 365 Cloud Licenses for 3 months, coaching, hackathons and the whole community. Premium adds more.",
    url: ORIGIN + "/membership.html",
  },
  {
    file: "podcast.html",
    title: "Tech Talk with Zoka — Sahaba Club Podcast",
    desc: "Conversations about AI, cloud and the people building with them. New episodes on YouTube and Spotify.",
    url: ORIGIN + "/podcast.html",
  },
  {
    file: "hackathons.html",
    title: "EduHackAI — Sahaba Club",
    desc: "The education hackathon for AI: build something that helps people learn. Open to students, teachers and anyone who wants to help.",
    url: ORIGIN + "/hackathons.html",
  },
];

function block(p) {
  return [
    "",
    "<!-- Share preview. Generated by tools/add-og-tags.mjs — keep the image at",
    "     1200x630: a square icon makes LinkedIn and Facebook fall back to a",
    "     thumbnail, which is what this replaced. -->",
    `<meta property="og:title" content="${p.title}">`,
    `<meta property="og:description" content="${p.desc}">`,
    `<meta property="og:image" content="${CARD}">`,
    '<meta property="og:image:width" content="1200">',
    '<meta property="og:image:height" content="630">',
    '<meta property="og:image:alt" content="Sahaba Club — the AI universe in the shape of a club">',
    `<meta property="og:url" content="${p.url}">`,
    '<meta property="og:site_name" content="Sahaba Club">',
    '<meta property="og:type" content="website">',
    '<meta name="twitter:card" content="summary_large_image">',
    `<meta name="twitter:title" content="${p.title}">`,
    `<meta name="twitter:description" content="${p.desc}">`,
    `<meta name="twitter:image" content="${CARD}">`,
    "",
  ].join("\r\n");
}

const APPLY = process.argv.includes("--apply");
let changed = 0;

for (const p of PAGES) {
  const path = "C:\\sctools\\scpush\\" + p.file;
  let src;
  try { src = readFileSync(path, "utf8"); } catch { console.log(`  ${p.file}: not found`); continue; }

  if (src.includes("og:image")) { console.log(`  ${p.file}: already has og:image — left alone`); continue; }

  // Insert after </title>, which every page has and which sits inside <head>
  // by definition. Anchoring on the description meta would be fragile: not
  // every page has one, and two pages put it before the title.
  const anchor = "</title>";
  const at = src.indexOf(anchor);
  if (at === -1) { console.log(`  ${p.file}: no </title> — SKIPPED`); continue; }

  const out = src.slice(0, at + anchor.length) + block(p) + src.slice(at + anchor.length);
  changed++;
  console.log(`  ${p.file}: + og tags`);
  if (APPLY) writeFileSync(path, out, "utf8");
}

console.log(`\n${APPLY ? "APPLIED" : "DRY RUN"}: ${changed} page(s)`);
if (!APPLY && changed) console.log("re-run with --apply to write");
