-- Sahaba Club — one-time import of the events that lived in events-data.js
-- ------------------------------------------------------------
-- Generated from the live EVENTS array so the move to the database loses
-- nothing. Run once, immediately after 0003. Running it twice would create
-- duplicates — there's no natural key to dedupe on, since two genuinely
-- different events could share a title and date.
--
-- After this runs, events-data.js is dead weight and the public page reads
-- from the `events` table instead.

insert into public.events
  (title, country, location, event_date, time_label, price_label, mode, tags,
   register_link, maps_link, image_url, brand, description, tier_required)
values
  ('AI Cafe by AIQUAINT ☕', 'UAE', 'Starbucks, Emirates Office Tower, Trade Center, Dubai', '2026-07-25', '10:00 AM – 11:00 AM', 'Free', 'In-Person', ARRAY['AI','Startups']::text[], 'https://luma.com/5pzl9z2x', 'https://www.google.com/maps/search/?api=1&query=Starbucks%20Emirates%20Towers%20Dubai', 'https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,dpr=1,anim=false,background=white,quality=75,width=800,height=420/event-social/ct/f44167f2-939c-4ef6-bb36-fc8566935f80.png', null, 'An intimate, no-slides coffee chat for AI folks — founders, builders, and researchers talking honestly about what''s really happening in AI right now. Limited seats, real conversations, zero panels.', 'all'),
  ('Founder Stories: The Journey Behind the Startup', 'UAE', 'Bookends, Dubai', '2026-07-25', '12:30 PM – 2:00 PM', 'Free', 'In-Person', ARRAY['Startups','Business']::text[], 'https://luma.com/f8vyi1kp', 'https://www.google.com/maps/search/?api=1&query=Bookends%20Dubai', 'https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,dpr=1,anim=false,background=white,quality=75,width=800,height=420/event-social/j4/aa20f2a3-db05-4a89-a338-07ac219fae2a.png', null, 'Honest, unscripted conversations with three UAE founders about the wins, the mistakes, and the pivots — no pitches, no lectures. Just real startup stories, audience Q&A, coffee, and community.', 'all'),
  ('UAE | MENA Software Engineers & QA Weekly Meetup', 'UAE', 'Dubai (exact address shared after registration)', '2026-07-26', '9:30 AM – 1:00 PM', 'Free', 'In-Person', ARRAY['Coding','AI']::text[], 'https://luma.com/e2shzo9m', 'https://www.google.com/maps/search/?api=1&query=25.21797176775973%2C55.28058148947743', 'https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,dpr=1,anim=false,background=white,quality=75,width=800,height=420/event-social/ep/91ce8d1b-8c1a-4787-b60f-c8891221d883.png', null, 'A weekly gathering for software engineers and QA folks across the UAE and MENA to connect, share, and grow together — this session dives into event-driven architecture, with a talk from Future Communications Company, Kuwait. Capacity capped at 35, so register early.', 'all'),
  ('AI.TV Community Meet-Up', 'UAE', 'Web3 Productions, Dubai', '2026-07-30', '6:30 PM – 9:00 PM', 'Free', 'In-Person', ARRAY['AI','Media']::text[], null, 'https://www.google.com/maps/search/?api=1&query=Web3%20Productions&query_place_id=ChIJ4SrR5t1tXz4Rrt7TKiVDaf4', 'assets/events/aitv-community-meetup.avif', null, 'Welcome to the home of AI creatives in the UAE. Hosted by AI.TV in partnership with ByteDance and Curious Refuge, this is your spot to meet, learn, share, and connect with fellow AI filmmakers and creatives. Open to anyone curious about AI filmmaking — all levels welcome.', 'all'),
  ('Build with n8n, Deploy in Minutes', 'UAE', 'Emirates Towers, Sheikh Zayed Rd, Dubai', '2026-08-01', '5:00 PM – 7:00 PM', 'Free', 'In-Person', ARRAY['Agentic','Coding']::text[], 'https://luma.com/n8n-easydep', 'https://www.google.com/maps/search/?api=1&query=Emirates%20Towers%20Sheikh%20Zayed%20Rd&query_place_id=ChIJy95l7pJCXz4RpIBbqDIVc78', 'https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,dpr=1,anim=false,background=white,quality=75,width=800,height=420/event-social/0z/4440f6bc-33b4-4dde-865a-c8e3f949f616.png', null, 'A hands-on session on shipping automations fast — live demos building an n8n workflow and deploying it with EasyDep, plus deployment best practices you can actually use. Pizza included.', 'all'),
  ('Founders Meetup - Dubai', 'UAE', 'WeWork, Dubai', '2026-08-05', '3:00 PM – 4:00 PM', 'Free', 'In-Person', ARRAY['Startups','Business']::text[], 'https://luma.com/jwuy4ni0', 'https://www.google.com/maps/search/?api=1&query=WeWork%20Dubai', 'https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,dpr=1,anim=false,background=white,quality=75,width=800,height=420/event-social/uo/995bb1c9-5b7d-40ae-ba53-3d7ed3a387ab.png', null, 'A relaxed meetup for founders and startup enthusiasts to swap stories, find collaborators, and build real relationships with fellow builders in Dubai.', 'all'),
  ('AI Business, Investment & Professional Meetup', 'UAE', 'JLT, Dubai', '2026-08-06', '6:30 PM – 8:30 PM', 'Free', 'In-Person', ARRAY['AI','Startups']::text[], 'https://luma.com/st1efdgi', 'https://www.google.com/maps/search/?api=1&query=JLT%20Dubai', 'https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,dpr=1,anim=false,background=white,quality=75,width=800,height=420/event-social/is/3446b86b-9c1d-4d65-9720-f7f7ebde72d8.png', null, 'A high-signal evening for builders, founders, and investors to swap ideas and spark collaborations — plus live AI demos from the DDS AI Challenge and the launch of the DDS Business Circle.', 'all'),
  ('Dubai AI Hub — Builder Lab #3: Voice Agents Hackathon', 'UAE', 'Dubai (venue TBA)', '2026-08-08', '8:30 AM – 5:30 PM', 'Free', 'In-Person', ARRAY['AI','Hackathon']::text[], 'https://luma.com/hai59p7q', null, 'https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,dpr=1,anim=false,background=white,quality=75,width=800,height=420/event-social/9b/58038cb0-2fd5-4b9d-89d9-59425aa40ae7.png', null, 'A one-day hackathon backed by ElevenLabs, Devin, and context.dev — build a voice-first AI agent that pulls live web data and actually talks back. Teams of five, free credits from every sponsor, real prizes on the line.', 'all'),
  ('Deal Catch: Pitch & Networking in Dubai', 'UAE', 'Josephs Cafe, Dubai', '2026-08-12', '7:00 PM – 9:30 PM', 'Paid — $28', 'In-Person', ARRAY['Startups','Investors']::text[], 'https://luma.com/6pvfpqjx', 'https://www.google.com/maps/search/?api=1&query=Josephs%20Cafe%20Dubai', 'https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,dpr=1,anim=false,background=white,quality=75,width=800,height=420/event-social/i7/5e6c7b54-3667-441c-83fc-c03a91a2a9ce.png', null, 'Pre-selected founders pitch live to a room of investors and professionals, hosted by Olivier Club and Fishman VC after 7 years of private events — now going public. Built for founders, VCs, angels, and anyone growing their network in Dubai''s startup scene.', 'all'),
  ('Crazy Clauders — B2B Networking for Founders & Business Owners', 'UAE', 'Wild Woven, DIFC / Downtown, Dubai', '2026-08-25', '6:30 PM – 8:00 PM', 'Free', 'In-Person', ARRAY['AI','Coding']::text[], 'https://luma.com/skn8qvje', 'https://www.google.com/maps/search/?api=1&query=Wild%20Woven%20DIFC%20Dubai', 'https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,dpr=1,anim=false,background=white,quality=75,width=800,height=420/event-social/e7/4f227084-096e-435a-89dc-cbd6e63fbb66.png', null, 'Dubai''s first-ever Clauders meetup, for founders and builders shipping with Claude and other AI tools. Show off what you''ve built, meet fellow Clauders, and grab a drink — on you, as a thanks to the host for the space.', 'all'),
  ('n8n Hackathon: Automate with K2', 'UAE', 'Emirates Towers, Sheikh Zayed Rd, Dubai', '2026-08-29', '2:00 PM – 7:00 PM', 'Free', 'In-Person', ARRAY['AI','Agentic']::text[], 'https://luma.com/n8n-wuqj', 'https://www.google.com/maps/search/?api=1&query=Emirates%20Towers%20Sheikh%20Zayed%20Rd&query_place_id=ChIJy95l7pJCXz4RpIBbqDIVc78', 'https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,dpr=1,anim=false,background=white,quality=75,width=800,height=420/event-social/5h/9d74724b-e028-4269-869f-b8559105029e.png', null, 'An n8n community hackathon focused on building automations with K2 — hosted by the n8n team and IFM Community. Hands-on building, real workflows, and a room full of automation builders.', 'all'),
  ('Runway — 4th Annual AI Film Festival', 'UAE', 'in5 Media, Dubai', '2026-09-01', '6:30 PM – 9:30 PM', 'Free', 'In-Person', ARRAY['AI','Media']::text[], 'https://luma.com/hpnd614f', 'https://www.google.com/maps/search/?api=1&query=in5%20Media%20Dubai', 'https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,dpr=1,anim=false,background=white,quality=75,width=800,height=420/event-social/tq/2e7e1c63-55f0-4166-ae3c-755dbd3a0e9d.png', null, 'A curated screening of the winning films from Runway''s AI Film Festival, followed by relaxed networking with filmmakers, creators, and commercial pros. Co-hosted by Yohan Wadia Studio and In5 — an evening of film, tech, and creativity.', 'all'),
  ('Microsoft Virtual Training Day: Transform Customer Experiences with AI', 'Online', 'Microsoft Digital Event', '2026-07-27', '7:30 AM – 8:45 AM GST', 'Free', 'Online', ARRAY['AI','Business']::text[], 'https://msevents.microsoft.com/event?id=2978625225', null, null, 'microsoft', 'A free Microsoft Learn training on using Copilot and agents in Dynamics 365 Sales and Customer Service to close deals faster, boost team productivity, and deliver more personalized customer experiences. Completing it unlocks 50% off the related certification exam.', 'all'),
  ('Microsoft Virtual Training Day: Introduction to Microsoft Azure', 'Online', 'Microsoft Digital Event', '2026-07-27', '7:30 AM – 11:45 AM GST', 'Free', 'Online', ARRAY['Cloud','Security']::text[], 'https://msevents.microsoft.com/event?id=2727739274', null, null, 'microsoft', 'A foundational, free Microsoft training covering core cloud concepts and Azure''s compute, networking, storage, identity, and security services — plus governance and cost-control tools. Finish it and get 50% off the Azure Fundamentals certification exam.', 'all'),
  ('Agent in a Day', 'Online', 'Microsoft Digital Event (delivered with Koenig Solutions)', '2026-07-27', '5:00 AM – 1:00 PM GST', 'Free', 'Online', ARRAY['Agentic','AI']::text[], 'https://msevents.microsoft.com/event?id=1844909682', null, null, 'microsoft', 'A full-day, hands-on workshop teaching anyone — business folks or developers — how to build agents fast with Microsoft Copilot Studio, with step-by-step labs and a Microsoft Certified Partner guiding you through it.', 'all'),
  ('Microsoft AI Envisioning Day: Publishing and Releasing Your AI Agent Solution', 'Online', 'Microsoft Digital Event', '2026-07-28', '7:30 AM – 8:30 AM GST', 'Free', 'Online', ARRAY['Agentic','Cloud']::text[], 'https://msevents.microsoft.com/event?id=279903695', null, null, 'microsoft', 'A free Microsoft session on turning your AI agent into a market-ready SaaS offering — multitenant architecture, the Microsoft Foundry and Azure Marketplace publishing workflow, and everything else it takes to launch on the commercial marketplace.', 'all'),
  ('Get Started with Microsoft 365 Copilot', 'Online', 'Microsoft Digital Event', '2026-07-28', '7:30 AM – 8:45 AM GST', 'Free', 'Online', ARRAY['AI','Business']::text[], 'https://msevents.microsoft.com/event?id=923449318', null, null, 'microsoft', 'A free, foundational Microsoft session on getting real productivity out of Copilot — summarizing Teams chats, drafting in Word, building PowerPoint decks, and writing better prompts, straight from Microsoft experts.', 'all'),
  ('Microsoft 365 Copilot Training for IT', 'Online', 'Microsoft Digital Event', '2026-07-28', '9:00 AM – 10:15 AM GST', 'Free', 'Online', ARRAY['AI','Coding']::text[], 'https://msevents.microsoft.com/event?id=76801058', null, null, 'microsoft', 'A free Microsoft training built for IT professionals — using Copilot to build project plans, analyze asset data in Excel, tighten up technical docs in Word, and summarize findings for stakeholders faster.', 'all'),
  ('Microsoft 365 Copilot Training for Sales', 'Online', 'Microsoft Digital Event', '2026-07-28', '10:30 AM – 11:30 AM GST', 'Free', 'Online', ARRAY['AI','Business']::text[], 'https://msevents.microsoft.com/event?id=3587052657', null, null, 'microsoft', 'A free Microsoft session for sales teams on using Copilot as an AI assistant — synthesizing sales activity from Teams, analyzing forecasts, and drafting promotions across Word, Outlook, and PowerPoint.', 'all'),
  ('Microsoft 365 Copilot Training for Executives', 'Online', 'Microsoft Digital Event', '2026-07-28', '11:30 AM – 12:30 PM GST', 'Free', 'Online', ARRAY['AI','Business']::text[], 'https://msevents.microsoft.com/event?id=1150827960', null, null, 'microsoft', 'A free Microsoft session built for executives — using Copilot to synthesize project updates in Teams, write executive briefings in Word, model budget forecasts in Excel, and get a Business Insights agent working for you.', 'all'),
  ('Microsoft 365 Copilot Training for Legal', 'Online', 'Microsoft Digital Event', '2026-07-28', '1:00 PM – 2:00 PM GST', 'Free', 'Online', ARRAY['AI','Business']::text[], 'https://msevents.microsoft.com/event?id=3553704114', null, null, 'microsoft', 'A free Microsoft session for legal professionals — using Copilot to summarize multi-page contracts, flag risk, track regulatory updates, and draft policy documents, with nuanced prompting techniques built for legal work.', 'all'),
  ('Regulatory Healthcare Analytics on Microsoft Fabric', 'Online', 'Meetup Online — MENA AI and Data Community', '2026-07-28', '7:00 PM – 8:00 PM GST', 'Free', 'Online', ARRAY['Cloud','Business']::text[], 'https://www.meetup.com/aicommunity/events/315599439/', null, 'https://secure-content.meetupstatic.com/images/classic-events/535398235/676x380.jpg', null, 'Breaking into healthcare analytics — the ten terms that unlock one of the most in-demand and least understood data careers, walked through on Microsoft Fabric.', 'all'),
  ('AI on Local Hardware: What Works, What Doesn''t, and Why', 'Online', 'Meetup Online — Advanced AI Concepts Global Dubai', '2026-08-01', '6:00 PM – 8:00 PM GST', 'Free', 'Online', ARRAY['AI','Coding']::text[], 'https://www.meetup.com/advanced-ai-concepts-global-dubai/events/315687406/', null, 'https://secure-content.meetupstatic.com/images/classic-events/535247973/676x380.jpg', null, 'Past the hype on running models locally — when open-weight models on your own hardware are genuinely the right tool, and when they honestly aren''t. With a guest speaker.', 'all'),
  ('MASTERCLASS: AI + Digital Marketing & Networking', 'UAE', 'Dubai (venue to be announced)', '2026-08-01', '2:00 PM – 4:00 PM', 'Free', 'In-Person', ARRAY['AI','Business']::text[], 'https://www.meetup.com/new-york-meetup-group-for-finding-purpose/events/315710993/', null, 'https://secure-content.meetupstatic.com/images/classic-events/535232557/676x380.jpg', null, 'Five practical marketing tasks done live, not talked about — you leave with publish-ready content, a competitor-backed strategy, a 30-day execution roadmap, and real connections.', 'all'),
  ('Dubai AI Meetup — Marina', 'UAE', 'Food Court, Dubai Marina Mall, Dubai', '2026-08-01', '7:00 PM – 10:00 PM', 'Free', 'In-Person', ARRAY['AI','Startups']::text[], 'https://www.meetup.com/dubai%E3%85%A4ai/events/315654253/', 'https://www.google.com/maps/search/?api=1&query=Dubai%20Marina%20Mall%20Food%20Court', 'https://secure-content.meetupstatic.com/images/classic-events/534841577/676x380.jpg', null, 'A weekly Saturday-evening AI gathering — usually around 30 people from very different backgrounds, swapping what they''re building. Relaxed, no slides.', 'all'),
  ('Dubai AI Meetup — DIFC', 'UAE', 'DIFC Food Court, Gate Avenue, Dubai', '2026-08-01', '7:30 PM – 10:30 PM', 'Free', 'In-Person', ARRAY['AI','Business']::text[], 'https://www.meetup.com/dubai-ai/events/315654525/', 'https://www.google.com/maps/search/?api=1&query=Gate%20Avenue%20DIFC%20Dubai', 'https://secure-content.meetupstatic.com/images/classic-events/526293913/676x380.jpg', null, 'The Dubai chapter of an AI and business meetup network that also runs in Shanghai and Mumbai. Meets above Carrefour Market in the DIFC food court.', 'all'),
  ('Master Agentic AI: Free Live Masterclass', 'Online', 'Meetup Online — DubAI and Data Professional', '2026-08-02', '12:00 PM – 1:00 PM GST', 'Free', 'Online', ARRAY['Agentic','AI']::text[], 'https://www.meetup.com/dubaidata/events/315645399/', null, 'https://secure-content.meetupstatic.com/images/classic-events/535398481/676x380.jpg', null, 'How modern AI agents actually reason, plan, pick tools and reach data to finish real tasks — taught by building applications live rather than talking theory.', 'all'),
  ('Get Google AI Certified — Cohort [5 of 7]', 'Online', 'Meetup Online — AI Professionals Dubai', '2026-08-03', '6:00 PM – 7:30 PM GST', 'Free', 'Online', ARRAY['AI','Business']::text[], 'https://www.meetup.com/ai-professionals-dubai/events/315673086/', null, 'https://secure.meetupstatic.com/photos/event/6/9/8/b/600_531567019.jpeg', null, 'Session five of the AI Professionals Dubai July cohort working through the Google AI certification together. Drop in to see how the group runs.', 'all'),
  ('Launch Your AI Business in 30 Days', 'UAE', 'Rove Downtown, Zabeel 2, Dubai', '2026-08-08', '6:00 PM – 8:00 PM', 'Free', 'In-Person', ARRAY['Startups','AI']::text[], 'https://www.meetup.com/spark-ventures/events/315757428/', 'https://www.google.com/maps/search/?api=1&query=Rove%20Downtown%20Dubai', 'https://secure.meetupstatic.com/photos/event/6/c/b/7/600_535287831.jpeg', null, 'An evening on Spark Ventures'' Start-Up in a Box — going from idea to launched AI venture in about 30 days without hiring developers, with real examples of what they''ve shipped.', 'all'),
  ('Get Google AI Certified — Cohort [6 of 7]', 'Online', 'Meetup Online — AI Professionals Dubai', '2026-08-10', '6:00 PM – 7:30 PM GST', 'Free', 'Online', ARRAY['AI','Business']::text[], 'https://www.meetup.com/ai-professionals-dubai/events/315675786/', null, 'https://secure.meetupstatic.com/photos/event/6/9/8/b/600_531567019.jpeg', null, 'Session six of the AI Professionals Dubai July cohort working through the Google AI certification together.', 'all'),
  ('Ai Everything Abu Dhabi', 'Abu Dhabi, UAE', 'ADNEC Centre', '2026-10-05', '5 – 7 Oct 2026', 'Paid', 'In-Person', ARRAY['AI','Mega Event']::text[], 'https://aieverythingabudhabi.com/home', null, null, null, 'The world''s leading AI show — summit on 5 Oct, expo 6 – 7 Oct. Global flagship.', 'all'),
  ('Dubai AI Festival', 'Dubai, UAE', 'Dubai World Trade Centre', '2026-10-26', '26 – 27 Oct 2026', 'Paid', 'In-Person', ARRAY['AI','Mega Event']::text[], 'https://dubaiaifestival.com/', null, null, null, 'Hosted by Dubai Future Foundation with DIFC — now at a bigger venue. 150+ sessions · 120+ countries.', 'all'),
  ('Global AI Show', 'Abu Dhabi, UAE', 'Space42 Arena', '2026-10-27', '27 – 28 Oct 2026', 'Paid', 'In-Person', ARRAY['AI','Mega Event']::text[], 'https://www.globalaishow.com/abu-dhabi/', null, null, null, 'Keynotes, panels and exhibitions across healthcare, finance and security. 5,000+ attendees · 100+ speakers.', 'all'),
  ('World AI Technology Expo', 'Dubai, UAE', 'Millennium Airport Hotel', '2026-11-17', '17 – 18 Nov 2026', 'Paid', 'In-Person', ARRAY['AI','Mega Event']::text[], 'https://worldaiexpo.io/', null, null, null, 'Enterprise AI in practice, plus the Entrepreneur & Investor Summit on 19 Nov. Three-day programme.', 'all'),
  ('GITEX GLOBAL', 'Dubai, UAE', 'Dubai Exhibition Centre, Expo City', '2026-12-07', '7 – 11 Dec 2026', 'Paid', 'In-Person', ARRAY['AI','Mega Event']::text[], 'https://www.gitex.com/gitex-global-2026', null, null, null, 'The world''s largest tech expo, with a dedicated AI & DeepTech track. 200,000+ attendees · 180 countries.', 'all');
