-- 0049 — Sahaba Club's own archive: 17 events, Aug 2023 – Mar 2024
-- ============================================================
--
-- Until now not one event in the database was organized by Sahaba Club. The
-- Events Hub — "events created by Sahaba Club or our partners" — had nothing
-- to show, and the partners section had no relationships to draw on. This is
-- the club's back catalogue, from the workbook Ahmed supplied.
--
-- ⚠ GENERATED by tools/generate-archive-events-seed.mjs from "Old Events.xlsx".
-- Do not hand-edit the block below — re-run the generator. Nine of these rows
-- carry Arabic titles or Arabic descriptions, where a transcription slip would
-- be invisible in review and would ship a wrong title onto a live page. The
-- generator also refuses to emit at all if any row would collide with a live
-- event, because 0048's unique index would abort the import.
--
-- ============================================================
-- Three things decided here, all of them stated rather than assumed
-- ============================================================
--
-- **Sahaba Club is a co-organizer on ALL seventeen.** Ahmed confirmed the
-- whole workbook is the club's own archive. Where the file names somebody else
-- — Microsoft, IEEE, Google DevFest, Aqua Energy Expo — that organizer is
-- added ALONGSIDE and marked `is_lead`, so their logo leads the card and the
-- club is still correctly recorded as a co-host. This is exactly the case that
-- made organizer a table in 0048: one row's organizer is literally
-- "Microsoft & Sahaba Club", and a single column would have had to discard one
-- of two true answers.
--
-- **"Ahmed Abdel Razek" means Sahaba Club.** Three rows record the founder's
-- name where later rows record the club's. Confirmed by Ahmed rather than
-- guessed — rewriting the attribution on somebody's own history is not a
-- judgement call to make quietly.
--
-- ⚠ **TIMES ARE READ AS UTC+04 (Gulf).** The workbook records wall-clock times
-- with no timezone at all. The club is UAE-registered, so Gulf time is the
-- reasonable reading — but `starts_at` is a timestamptz and storing one means
-- committing to an offset. For events three years past, displayed as dates,
-- an hour changes nothing visible. If these were actually run on Cairo time
-- (UTC+2) every stored instant is two hours late and one UPDATE fixes it.
--
-- ---- What is deliberately absent -------------------------------------------
--
-- **No images.** The workbook has none, so all seventeen land with
-- `image_url` null and will fall back to the default square artwork. They are
-- the first candidates for the upload control being built next.
--
-- **`mode` is 'Online' on every row and `country` is null.** These were
-- webinars. ⚠ Two are probably not: "Sahaba Club @ GosTech - IEEE BU" runs
-- five hours from 10:00 at a university, and the Google DevFest session reads
-- like an in-person conference slot. Both are flagged in the verification
-- block rather than guessed at here — marking an event In-Person also means
-- claiming a country, and inventing a venue is worse than leaving it open.
--
-- **16 of 17 carry a recording.** On-Demand was dropped as a tab, but these
-- YouTube links are the club's back catalogue and the event page offers them.

-- GENERATED by tools/generate-archive-events-seed.mjs from "Old Events.xlsx"
-- 17 events. Do not hand-edit: re-run the generator.
-- Times read as UTC+04 (Gulf); the workbook records no timezone.

insert into public.events
  (title, slug, description, event_date, starts_at, duration_minutes, presenter,
   recording_url, mode, country, price_label, tier_required, is_published)
values
  ('Welcome to Sahaba Club - Unleashing the Power of Technology Together!', 'welcome-to-sahaba-club-unleashing-the-power-of-technology-together-2023', 'Are you a technology passionate and eager to connect with like-minded individuals, learn from expert coaches, and achieve your goals in the world of technology? 

Welcome to Sahaba Club, the ultimate platform designed exclusively for tech lovers like you!

Join us on August 2nd for a special webinar session, where we will warmly welcome all our early registrants and provide a comprehensive guide on how to make the most of your Sahaba Club membership & Microsoft 365 license.

Whether you''re an aspiring developer, a tech entrepreneur, or simply someone who loves to explore the wonders of technology, Sahaba Club is the perfect place for you. We believe that together, we can take technology and innovation to new heights!

Mark your calendars for August 2nd and embark on this exhilarating tech adventure with Sahaba Club.', '2023-08-02', '2023-08-02 20:30:00+04'::timestamptz, 90, 'Ahmed Abdel Razek', 'https://youtu.be/ntx9qAbYiYI?si=7S59xTxnRvoWHY2C', 'Online', null, 'Free', 'all', true),
  ('The Power of Code: High VS Low & No Code', 'the-power-of-code-high-vs-low-no-code-2023', 'Are you passionate about programming and eager to explore the latest technologies? 

This is the perfect opportunity for you!

Join us for an exciting webinar hosted by Sahaba Club! 

Our special guest, Wessam Combal, is a tech-savvy genius with hands-on experience, a creative vision, and an entrepreneurial mindset. 

Don''t miss the chance to learn from the best!

Discover the limitless possibilities of coding and unleash your creativity with high and low-code solutions! 

Join us for an eye-opening session!', '2023-08-09', '2023-08-09 20:30:00+04'::timestamptz, 90, 'Wessam Combal', 'https://youtu.be/FZ6B--Vm7BQ?si=gqRPjy9zkZsDkTRa', 'Online', null, 'Free', 'all', true),
  ('AI for Everyone: How to Build Your Skills and Career in the AI World', 'ai-for-everyone-how-to-build-your-skills-and-career-in-the-ai-world-2023', 'Are you curious about the world of Artificial Intelligence but don''t know where to start?

Join us for an engaging and informative webinar that will equip you with the essentials to kickstart your AI journey! 🚀🤖

🔍 Agenda:

Decoding Artificial Intelligence (AI) vs. Machine Learning (ML): What is the difference between AI and ML, and what are the main types and applications of both. 🤖🧠 

Launching Your AI Career: Discover the first steps and strategies to embark on a successful path in the field of AI.  🚀🔧

Unleashing AI on the Cloud: Explore the power of AI in the cloud computing 🌐 ☁️💡

You will have the opportunity to ask me any questions you have about AI and ML, and I will be happy to answer them. 😃', '2023-08-23', '2023-08-23 20:30:00+04'::timestamptz, 90, 'Ahmed Abdel Razek', 'https://youtu.be/e3J3z4u7zl0?si=n5vqeXq6aN1TPi4x', 'Online', null, 'Free', 'all', true),
  ('How to use Microsoft 365 to boost your tech skills with Sahaba Club', 'how-to-use-microsoft-365-to-boost-your-tech-skills-with-sahaba-club-2023', 'Agenda:

Introduction to Sahaba Club and its vision
Overview of Microsoft 365 and its applications
How to access and activate your free Microsoft 365 license as a Sahaba Club member
How to register for Sahaba Club and join its online community
Q&A session

Who should attend:

Anyone who is interested in learning or improving their technology skills using Microsoft 365 and joining a supportive online platform.

Benefits from the online webinar:

Learn about the features and benefits of Microsoft 365 and how it can help you achieve your learning goals
Get your free Microsoft 365 license and start using its applications right away
Become a part of Sahaba Club and connect with other learners and coaches
Get your questions answered by the Sahaba Club team', '2023-08-30', '2023-08-30 20:30:00+04'::timestamptz, 90, 'Ahmed Abdel Razek', 'https://youtu.be/HM4HM95N7QU', 'Online', null, 'Free', 'all', true),
  ('Sahaba Club @ GosTech - IEEE BU', 'sahaba-club-gostech-ieee-bu-2023', 'مغامرتنا السنه دي مغامره من عالم تاني، و رفيقنا في المغامره دي هو Ghost
بس مش زي اللي في بالك 🤓
سنه 1983، كتاب سحري سحب صاحبنا الghost و حبسه في عالم تاني، و علشان يتحرر و يرجع لعالمنا الطبيعي، استعان بينا و احنا اللي هنساعده بنفس الكتاب اللي حبسه 🧐 و دا عن طريق اتباع إرشادات الكتاب لبناء عربيه بتتحكرك بإشارات الايد🖐🏻
و علي مدار 5 ايام في ايفنت ghostech هتتعلم انت كمان كل اللي محتاج تعرفه عن ال Arduino و Machine Learning و Computer Vision علشان تعرف ازاي تبني العربية🚘
و تابعوا معانا علشان تعرفوا ال ghost بتاعنا و ايه اللي خلاه يتحبس في العالم التاني و ازاي هيتحرر


"Our adventure this year is a journey from another world, and our companion in this escapade is GHOST. However, it''s not quite what you might have in mind. 🤓
In the year 1983, a magical book pulled our friend, the ghost, and imprisoned him in another world. To free him and bring him back to our normal world, he sought our help. We are the ones who will assist him using the same book that entrapped him. 🧐 This involves following the book''s instructions to construct a car that operates through hand signals. 🖐🏻
During the 5-day GHOSTECH event, you''ll also acquire all the necessary knowledge about Arduino, Machine Learning, and Computer Vision. This knowledge will enable you to build the car. 🚘
Join us to learn about our ghost, the reasons behind his imprisonment in the other world, and how he will achieve his freedom. 🤔', '2023-09-07', '2023-09-07 10:00:00+04'::timestamptz, 300, 'Ahmed Abdel Razek', 'https://youtu.be/HDUVb9o_v8s?si=ozUHxLmCfQA8tbNo', 'Online', null, 'Free', 'all', true),
  ('Microsoft Global Hackathon: Team Selection Workshop!', 'microsoft-global-hackathon-team-selection-workshop-2023', 'Build, innovate, and HackTogether! It''s time to get started building solutions with AI in the Power Platform!



HackTogether is your playground for experimenting with the new Copilot and AI features in the Power Platform. With mentorship from Microsoft experts and access to the latest tech, you will learn how to build solutions in Power Platform by leveraging AI. The possibilities are endless for what you can create... plus you can submit your hack for a chance to win exciting prizes! 🥳



The hackathon starts on September 14th - 28th. Registration will open up soon so check this page for more updates on how to register!', '2023-09-09', '2023-09-09 11:00:00+04'::timestamptz, 120, 'Mostafa Kotb', null, 'Online', null, 'Free', 'all', true),
  ('ابدأ تعلم الذكاء الاصطناعي بسهولة', 'sahaba-club-webinar-2023-09-09', 'دعوة عامة لحضور ويبنار أونلاين مجاني بعنوان *"ابدأ تعلم الذكاء الاصطناعي بسهولة"*
💥الويبنار برعاية وتنظيم منصة أكوا إنيرجي إكسبو (المعرض الافتراضي لشركات ومنتجات المياه والطاقة)
📱سيتم عقد الويبنار من خلال برنامج Google Meet بمشيئة الله يوم السبت ٩ سبتمبر لمدة ساعتين من الساعة ٧ إلى ٩ مساءً بتوقيت القاهرة 
والسعودية
🌎 يمنح المشاركين في البث المباشر شهادة حضور للويبنار
🎤 يقدم الويبنار 
 المحاضر المهندس/ أحمد عبد الرازق 
 🥇 حاصل على شهادة ماجستير من جامعة تكساس في "الذكاء الصناعي للقادة" 
 🥇معتمد من ميكروسوفت في "أساسيات الذكاء الصناعي" 
🥇حاصل علي شهادة "أدوات الذكاء الصناعي السحابية"
⚫ موضوعات الويبنار
-مفهوم الذكاء الصناعي وتعلم الآلة
- كيف تبني مسارك المهني في مجال الذكاء الصناعي
- ما هي أدوات ميكروسوفت السحابية للذكاء الصناعي
- انشاء تطبيقات الذكاء الصناعي وتحليل البيانات وبناء نماذج تعلم الآلة ونشرها على سحابة ميكروسوفت
-الإجابة على الاستفسارات
🏃‍♂المشاركة في الويبنار من خلال الانضمام لجروب منصة أكوا إنرجي إكسبو على تليجرام
https://t.me/AquaEnergyExpo', '2023-09-09', '2023-09-09 19:00:00+04'::timestamptz, 120, 'Ahmed Abdel Razek', 'https://www.youtube.com/watch?v=66FWNjLcj4w', 'Online', null, 'Free', 'all', true),
  ('Hack Together: Power Platform AI Global Hack 2023', 'hack-together-power-platform-ai-global-hack-2023-2023', 'فريق سحابة كلوب قرر يقبل التحدي ويدخل المسابقة ويفوز إن شاء الله
شجع فريقك...

  عشان انت مهتم بالتكنولوجيا لازم تعرف ان شركة مايكروسوفت العالمية بتنظم مسابقة دورية لتشجيع المطورين والمهندسين على إبداع وتطوير حلول تكنولوجية مبتكرة باستخدام منتجاتها وخدماتها.

ده جدول ندوات مايكروسوفت وهتكون متاحة للجميع لو عاوز تعيش الأجواء

- Kickoff: Ready, Set, Hack: Do more with AI in the Power Platform
https://www.youtube.com/watch?v=vrwjre_n3qw

- Intro to Power Platform Copilots
https://www.youtube.com/watch?v=-cU-1bpmk-k

- Get started with AI Builder in the Power Platform
https://www.youtube.com/watch?v=iEE7FTi05hE

- Leveraging Azure OpenAI Service in the Power Platform
https://www.youtube.com/watch?v=LbbEY2Juq90

- How to submit your projects on GitHub
https://www.youtube.com/watch?v=S5Zk_0lvAdM

- Wrap up and take action: Join our community for the next Big Thing!
https://www.youtube.com/watch?v=x44dWCgqJQ4', '2023-09-28', '2023-09-28 20:00:00+04'::timestamptz, 120, 'Sahaba Club Team', 'https://youtu.be/64O5Sp05C3Q?si=ungBfZDBYBIlrPWU', 'Online', null, 'Free', 'all', true),
  ('الذكاء الصناعي في خدمتك', 'sahaba-club-webinar-2023-10-06', 'هل ترغب في تحسين جودة وتسريع إنجاز مهام عملك اليومية؟
 هل ترغب في استخدام أحدث  تطبيقات الذكاء الاصطناعي لتسهيل حياتك المهنية؟
 إذاً، لا تفوت فرصة المشاركة في ويبينار بعنوان الذكاء الصناعي في خدمتك💼🚀

انضم إلينا في هذا الحدث  حيث سنكشف لك كيف يمكنك الاستفادة من أحدث تطبيقات الذكاء الاصطناعي لتحسين أداءك في العمل وتسهيل مهامك اليومية.

 ستتعلم كيف يمكن للتقنية أن تكون شريكًا لك في تحقيق الكفاءة والإنتاجية العالية. 💪💡📱

سنقدم لك نصائح قيمة ونماذج عملية لتطبيقات الذكاء الاصطناعي التي يمكنك استخدامها لتحويل عملك اليومي إلى تجربة سلسة ومذهلة.

 ستكتشف كيف يمكن للتكنولوجيا أن تكون حلاً لتحدياتك وتساعدك في تحقيق أهدافك المهنية بسهولة وفعالية. 🌐📈💻', '2023-10-06', '2023-10-06 19:00:00+04'::timestamptz, 120, 'Mostafa Kotb', 'https://www.youtube.com/watch?v=dQliQ0TZWkg', 'Online', null, 'Free', 'all', true),
  ('AI on Cloud - الذكاء الاصطناعي في الحوسبة السحابية', 'ai-on-cloud-2023', '👋 Hello! In this webinar, we will introduce you to the World of Artificial Intelligence (AI) on the Cloud. You will learn: 

What AI is? 
Why it is important?, 
How Cloud computing can help you get started with AI?. 

We will also discuss Generative AI, which is a type of AI that can create new content, such as text, images, and music.



Microsoft will be used as an example throughout the webinar.

Points to Discuss:

What is AI?
Why is AI important?
What is Cloud computing?
How can Cloud computing help you with AI?
What is Generative AI?
How can you use AI on the Cloud to improve your business or life?
⁠Roadmap for learning cloud computing with Microsoft, AWS, or Google.

AI and Cloud Computing are rapidly growing fields with many job opportunities. If you are interested in a career in cloud computing, consider joining Sahaba Club. We offer many resources to help you learn the skills you need. Good luck! 😊', '2023-11-15', '2023-11-15 19:00:00+04'::timestamptz, 120, 'Ahmed Abdel Razek', 'https://www.youtube.com/watch?v=wk_bRmIJ5Wk&t=3s', 'Online', null, 'Free', 'all', true),
  ('Enjoy Learning Using Microsoft AI Tools', 'enjoy-learning-using-microsoft-ai-tools-2023', 'This 2-hour webinar will introduce you to Microsoft AI tools that can enhance your teaching and learning experience. We will cover the following topics:

Bing Chat and Image Creator: Learn how to use AI-powered chat and image generation to create engaging and interactive learning experiences.
Immersive Reader: Discover how Immersive Reader can help improve your reading comprehension and fluency.
AI-powered Copilot for the Web: Explore how the AI-powered Copilot for the Web can help you write more effectively and efficiently.
Reading Coach and Reading Progress: Get personalized feedback on your reading skills and track your progress over time.
Speaking Coach: Enhance your speaking skills with the help of the Speaking Coach.
Benefits of attending this webinar:

Learn about powerful AI tools that can help you teach and learn more effectively.
Discover how to create engaging and interactive learning experiences.
Improve your reading comprehension, fluency, and speaking skills.
Who should attend this webinar:

Teachers
Students
Parents
Anyone interested in learning more about Microsoft AI tools', '2023-11-22', '2023-11-22 19:00:00+04'::timestamptz, 120, 'Mona Murad', 'https://youtu.be/L12hVXbvUtQ', 'Online', null, 'Free', 'all', true),
  ('Tech Sales Mastery: Elevate Your Skills and Earn Top Dollars', 'tech-sales-mastery-elevate-your-skills-and-earn-top-dollars-2023', 'Details:

This 2-hour webinar will introduce you to the world of technology sales. You will learn about the different types of technology sales jobs, the skills you need to succeed, and how to get started in this exciting career. We will also hear from Tamer Sabry, a Sales Expert with over 23 years of experience in the technology industry. 

6 Points to Discuss in the Webinar: 

1- What is technology sales? 
2- The different types of technology sales jobs 
3- The skills you need to succeed in technology sales 
4- How to get started in technology sales 
5- Tips for success from a sales expert 
6- Q&A with Tamer Sabry', '2023-11-29', '2023-11-29 19:00:00+04'::timestamptz, 120, 'Tamer Sabry', 'https://youtu.be/WyZUdxEunj8', 'Online', null, 'Free', 'all', true),
  ('Find Your Dream Job on LinkedIn', 'find-your-dream-job-on-linkedin-2023', 'Join LinkedIn expert Osama Qotb to maximize LinkedIn''s power for career advancement.

Key Topics:

1- Crafting a compelling profile
2- Expanding your professional network
3- Creating high-quality content
4- Leveraging LinkedIn groups and communities
5- Utilizing LinkedIn for job searching

Benefits of attending:

- Enhance your professional life with LinkedIn
- Create an attention-grabbing profile
- Master networking strategies
- Develop engaging content creation skills
- Advance your career with LinkedIn

Who Should Attend:

- Individuals new to LinkedIn
- Job seekers and career changers
- Professionals seeking to enhance their LinkedIn presence
- Anyone interested in maximizing LinkedIn''s potential', '2023-12-06', '2023-12-06 19:00:00+04'::timestamptz, 120, 'Osama Qotb', 'https://youtu.be/ahwa7TvfOm4?si=VCN93qSgd8Zjs-q9', 'Online', null, 'Free', 'all', true),
  ('Microsoft Free Learning Tools your Golden Opportunity', 'microsoft-free-learning-tools-your-golden-opportunity-2023', '🚀 Discover the World of Training with Microsoft Learn in a Free webinar to Enhance Your Skills! 🌐💼

In this webinar, you will learn:
📌 How to Create a Free Account on Microsoft Learn:
Easy steps to create a personal account giving you access to a diverse library of courses.
 
📌 Access to Free Professional Courses:
Overview of free professional courses available for all levels, ages, and specializations.
 
📌 Obtaining a Master Trainer Certificate:
Exclusive opportunity to earn a certified certificate from Microsoft.
 
📌 Recording Training Hours in Microsoft EduTrucker:
How to document your training experiences effectively.
 
📌 Access to Ready-Made Training Materials:
How to utilize Microsoft Learn resources to prepare training materials tailored to your needs.', '2023-12-20', '2023-12-20 19:00:00+04'::timestamptz, 120, 'Mona Murad', 'https://youtu.be/L12hVXbvUtQ?si=nHTRlPUYZtOw-mE0', 'Online', null, 'Free', 'all', true),
  ('Cloud Computing', 'cloud-computing-2023', '☁️🚀 Sahaba Club''s Participation in a Cloud Computing Session!

Sahaba Club is committed to sharing knowledge and innovation, which is why we have joined a session on Cloud Computing!

 Eng. Ahmed Abdel Razek , CEO of Sahaba Club, will be participating in a session on Cloud Computing full of in-depth analysis and rich exchanges about the latest trends and techniques in Cloud Computing.
 
📅 Date: Saturday, December 9th
📍 Location: College of Artificial Intelligence, Menoufia University', '2023-12-10', '2023-12-10 14:30:00+04'::timestamptz, 120, 'Ahmed Abdel Razek', 'https://youtu.be/2Bscm8-PBf8?si=KqYakNU7HI5FBwz0', 'Online', null, 'Free', 'all', true),
  ('Unlock the AI Power - Play with Microsoft Copilot', 'unlock-the-ai-power-play-with-microsoft-copilot-2024', 'Description:

🚫 No code? No problem! Master Microsoft''s AI copilot in this interactive webinar and build custom apps & automation without writing a single line.
🎮 Play live with Copilot for Power Apps & Power Automate. Use AI magic to create stunning apps, automate tedious tasks, and impress your colleagues.
💪 Discover Sales Copilot''s superpowers: Boost your sales skills with AI-powered insights and automation.
🌐 Zero tech experience needed! We''ll guide you step-by-step through fun, hands-on scenarios.
Bonus:

🔍 Q&A session with Microsoft experts
📚 Downloadable resources and cheatsheet
Call to Action:

🚀 Register now to unlock your inner power user and wow your colleagues with AI-powered productivity!', '2024-03-20', '2024-03-20 19:00:00+04'::timestamptz, 60, 'Ahmed Abdel Razek', 'https://youtu.be/1hrx5LH7m0s?si=1bKvOW5enJh6RQvY', 'Online', null, 'Free', 'all', true),
  ('Hack or Be Hacked: Decoding Cloud Security Threats', 'hack-or-be-hacked-decoding-cloud-security-threats-2024', 'Learn:

Real-world cyber threats & how the cloud protects. ‍♂️
Microsoft Azure''s robust security features for your data.
Practical tips for stronger passwords, safer browsing, and more.
Ask:

Get expert answers to all your cloud security questions. ❓

Gain:

Confidence & control over your online life. Secure your future with the cloud!', '2024-01-03', '2024-01-03 19:00:00+04'::timestamptz, 120, 'Hazem Waddah', 'https://youtu.be/XYbtH5H5NDo?si=9fYk1gcTM4Pt2bcY', 'Online', null, 'Free', 'all', true)
on conflict do nothing;

-- Organizers. Sahaba Club on every row — Ahmed confirmed the whole file is the
-- club's own archive, and 0048's rule is that an event is ours when Sahaba Club
-- is among its organizers. is_lead marks the named co-organizer where there is
-- one, so their logo leads the card.
insert into public.event_organizers (event_id, organizer_id, is_lead)
select e.id, o.id, true from public.events e, public.organizers o
 where e.slug = 'welcome-to-sahaba-club-unleashing-the-power-of-technology-together-2023' and o.slug = 'sahaba-club'
on conflict do nothing;
insert into public.event_organizers (event_id, organizer_id, is_lead)
select e.id, o.id, true from public.events e, public.organizers o
 where e.slug = 'the-power-of-code-high-vs-low-no-code-2023' and o.slug = 'sahaba-club'
on conflict do nothing;
insert into public.event_organizers (event_id, organizer_id, is_lead)
select e.id, o.id, true from public.events e, public.organizers o
 where e.slug = 'ai-for-everyone-how-to-build-your-skills-and-career-in-the-ai-world-2023' and o.slug = 'sahaba-club'
on conflict do nothing;
insert into public.event_organizers (event_id, organizer_id, is_lead)
select e.id, o.id, true from public.events e, public.organizers o
 where e.slug = 'how-to-use-microsoft-365-to-boost-your-tech-skills-with-sahaba-club-2023' and o.slug = 'sahaba-club'
on conflict do nothing;
insert into public.event_organizers (event_id, organizer_id, is_lead)
select e.id, o.id, true from public.events e, public.organizers o
 where e.slug = 'sahaba-club-gostech-ieee-bu-2023' and o.slug = 'ieee'
on conflict do nothing;
insert into public.event_organizers (event_id, organizer_id, is_lead)
select e.id, o.id, false from public.events e, public.organizers o
 where e.slug = 'sahaba-club-gostech-ieee-bu-2023' and o.slug = 'sahaba-club'
on conflict do nothing;
insert into public.event_organizers (event_id, organizer_id, is_lead)
select e.id, o.id, true from public.events e, public.organizers o
 where e.slug = 'microsoft-global-hackathon-team-selection-workshop-2023' and o.slug = 'sahaba-club'
on conflict do nothing;
insert into public.event_organizers (event_id, organizer_id, is_lead)
select e.id, o.id, true from public.events e, public.organizers o
 where e.slug = 'sahaba-club-webinar-2023-09-09' and o.slug = 'aqua-energy-expo'
on conflict do nothing;
insert into public.event_organizers (event_id, organizer_id, is_lead)
select e.id, o.id, false from public.events e, public.organizers o
 where e.slug = 'sahaba-club-webinar-2023-09-09' and o.slug = 'sahaba-club'
on conflict do nothing;
insert into public.event_organizers (event_id, organizer_id, is_lead)
select e.id, o.id, true from public.events e, public.organizers o
 where e.slug = 'hack-together-power-platform-ai-global-hack-2023-2023' and o.slug = 'microsoft'
on conflict do nothing;
insert into public.event_organizers (event_id, organizer_id, is_lead)
select e.id, o.id, false from public.events e, public.organizers o
 where e.slug = 'hack-together-power-platform-ai-global-hack-2023-2023' and o.slug = 'sahaba-club'
on conflict do nothing;
insert into public.event_organizers (event_id, organizer_id, is_lead)
select e.id, o.id, true from public.events e, public.organizers o
 where e.slug = 'sahaba-club-webinar-2023-10-06' and o.slug = 'sahaba-club'
on conflict do nothing;
insert into public.event_organizers (event_id, organizer_id, is_lead)
select e.id, o.id, true from public.events e, public.organizers o
 where e.slug = 'ai-on-cloud-2023' and o.slug = 'sahaba-club'
on conflict do nothing;
insert into public.event_organizers (event_id, organizer_id, is_lead)
select e.id, o.id, true from public.events e, public.organizers o
 where e.slug = 'enjoy-learning-using-microsoft-ai-tools-2023' and o.slug = 'sahaba-club'
on conflict do nothing;
insert into public.event_organizers (event_id, organizer_id, is_lead)
select e.id, o.id, true from public.events e, public.organizers o
 where e.slug = 'tech-sales-mastery-elevate-your-skills-and-earn-top-dollars-2023' and o.slug = 'sahaba-club'
on conflict do nothing;
insert into public.event_organizers (event_id, organizer_id, is_lead)
select e.id, o.id, true from public.events e, public.organizers o
 where e.slug = 'find-your-dream-job-on-linkedin-2023' and o.slug = 'sahaba-club'
on conflict do nothing;
insert into public.event_organizers (event_id, organizer_id, is_lead)
select e.id, o.id, true from public.events e, public.organizers o
 where e.slug = 'microsoft-free-learning-tools-your-golden-opportunity-2023' and o.slug = 'sahaba-club'
on conflict do nothing;
insert into public.event_organizers (event_id, organizer_id, is_lead)
select e.id, o.id, true from public.events e, public.organizers o
 where e.slug = 'cloud-computing-2023' and o.slug = 'google-devfest'
on conflict do nothing;
insert into public.event_organizers (event_id, organizer_id, is_lead)
select e.id, o.id, false from public.events e, public.organizers o
 where e.slug = 'cloud-computing-2023' and o.slug = 'sahaba-club'
on conflict do nothing;
insert into public.event_organizers (event_id, organizer_id, is_lead)
select e.id, o.id, true from public.events e, public.organizers o
 where e.slug = 'unlock-the-ai-power-play-with-microsoft-copilot-2024' and o.slug = 'sahaba-club'
on conflict do nothing;
insert into public.event_organizers (event_id, organizer_id, is_lead)
select e.id, o.id, true from public.events e, public.organizers o
 where e.slug = 'hack-or-be-hacked-decoding-cloud-security-threats-2024' and o.slug = 'sahaba-club'
on conflict do nothing;

-- ============================================================
-- Verification
-- ============================================================
--
-- 1. All seventeen landed and none was silently swallowed by `on conflict do
--    nothing` (expect 17 and 63):
--
--   select count(*) from public.events where starts_at is not null;
--   select count(*) from public.events;
--
-- 2. ⚠ EVERY archived event is ours. This is the rule the whole Events Hub
--    rests on — "Sahaba Club is among its organizers" — so it is checked by
--    asking the view, not by trusting the inserts (expect 17, and 0 rows from
--    the second query):
--
--   select count(*) from public.event_organizer_list where is_ours;
--
--   select e.slug, e.title from public.events e
--    where e.starts_at is not null
--      and e.id not in (select event_id from public.event_organizer_list where is_ours);
--
-- 3. The four co-organized events kept BOTH organizers — the case a single
--    column would have destroyed (expect 4 rows, each with 2 names):
--
--   select event_slug, organizer_names, categories
--     from public.event_organizer_list
--    where array_length(organizer_names, 1) > 1
--    order by event_slug;
--
-- 4. Slugs are unique and the Arabic-titled pair got readable ones rather than
--    `event-2023` (expect 2 rows, both sahaba-club-webinar-<date>):
--
--   select slug, title from public.events
--    where slug like 'sahaba-club-webinar-%' order by slug;
--
--   select count(*) - count(distinct slug) as duplicate_slugs from public.events;  -- expect 0
--
-- 5. Recordings arrived (expect 16):
--
--   select count(*) from public.events where recording_url is not null;
--
--    ⚠ Two events share one recording — rows 11 and 14 of the workbook both
--    point at L12hVXbvUtQ. That is what the source says, so it is imported
--    faithfully; it is probably a copy-paste in the original and worth a look:
--
--   select recording_url, count(*), string_agg(title, ' | ')
--     from public.events where recording_url is not null
--    group by recording_url having count(*) > 1;
--
-- 6. ⚠ THE TWO PROBABLY-NOT-ONLINE EVENTS. Imported as Online because the
--    workbook does not say otherwise; correct them if they were in person,
--    remembering that In-Person also needs a country for the new filter:
--
--   select slug, title, event_date, duration_minutes, mode, country
--     from public.events
--    where slug like '%gostech%' or slug like '%cloud-computing%';
--
-- 7. The Hub has something to show, and the partners section has organizers
--    to draw (expect a non-zero past count, and 4 partners with events):
--
--   select count(*) as past_ours
--     from public.event_organizer_list l
--     join public.events e on e.id = l.event_id
--    where l.is_ours and e.event_date < current_date;
--
--   select o.name, o.category, o.is_partner, count(eo.event_id) as events
--     from public.organizers o
--     left join public.event_organizers eo on eo.organizer_id = o.id
--    group by o.id, o.name, o.category, o.is_partner
--    order by events desc, o.sort_order;
--
-- 8. ⚠ AS AN ORDINARY MEMBER — the archive is public, as it should be
--    (these are published past events, visible to visitors too):
--
--   select count(*) from public.events where starts_at is not null;   -- expect 17
--   select count(*) from public.event_organizer_list;                 -- expect 17
--   update public.events set title = 'x' where slug like 'sahaba%';   -- expect 0 rows / refused
